name: Manual Tap Update
on:
  workflow_dispatch:
    inputs:
      tag:       { description: "vX.Y.Z", required: true }
      src_owner: { description: "Source owner", required: true, default: "theGeekist" }
      src_repo:  { description: "Source repo",  required: true, default: "skeletor" }

permissions: { contents: write }

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checksums
        id: sums
        shell: bash
        run: |
          set -euo pipefail
          TAG="${{ inputs.tag }}"
          BASE="https://github.com/${{ inputs.src_owner }}/${{ inputs.src_repo }}/releases/download/${TAG}"
          fetch() { curl -fsSL "$1" -o "$2"; sha256sum "$2" | awk '{print $1}'; }
          echo "mac_arm=$(fetch "$BASE/skeletor-macos-aarch64-apple-darwin.tar.gz" macos-arm64.tgz)" >> $GITHUB_OUTPUT
          echo "mac_x64=$(fetch "$BASE/skeletor-macos-x86_64-apple-darwin.tar.gz" macos-x64.tgz)" >> $GITHUB_OUTPUT
          echo "lnx_x64=$(fetch "$BASE/skeletor-ubuntu-x86_64-unknown-linux-gnu.tar.gz" linux-x64.tgz)" >> $GITHUB_OUTPUT

      - name: Update Formula
        shell: bash
        run: |
          mkdir -p Formula
          cat > Formula/skeletor.rb <<'RUBY'
          class Skeletor < Formula
            desc "Two-way scaffolding CLI (apply + snapshot)"
            homepage "https://github.com/__OWNER__/__REPO__"
            license "MIT"
          
            on_macos do
              on_arm do
                url "https://github.com/__OWNER__/__REPO__/releases/download/__TAG__/skeletor-macos-aarch64-apple-darwin.tar.gz"
                sha256 "__MAC_ARM__"
              end
              on_intel do
                url "https://github.com/__OWNER__/__REPO__/releases/download/__TAG__/skeletor-macos-x86_64-apple-darwin.tar.gz"
                sha256 "__MAC_X64__"
              end
            end
          
            on_linux do
              on_intel do
                url "https://github.com/__OWNER__/__REPO__/releases/download/__TAG__/skeletor-ubuntu-x86_64-unknown-linux-gnu.tar.gz"
                sha256 "__LNX_X64__"
              end
            end
          
            def install
              bin.install "skeletor"
            end
          
            test do
              assert_match "skeletor", shell_output("#{bin}/skeletor --help")
            end
          
            livecheck do
              url :stable
              strategy :github_latest
            end
          end
          RUBY
          sed -i "s|__OWNER__|${{ inputs.src_owner }}|g" Formula/skeletor.rb
          sed -i "s|__REPO__|${{ inputs.src_repo }}|g" Formula/skeletor.rb
          sed -i "s|__TAG__|${{ inputs.tag }}|g" Formula/skeletor.rb
          sed -i "s|__MAC_ARM__|${{ steps.sums.outputs.mac_arm }}|g" Formula/skeletor.rb
          sed -i "s|__MAC_X64__|${{ steps.sums.outputs.mac_x64 }}|g" Formula/skeletor.rb
          sed -i "s|__LNX_X64__|${{ steps.sums.outputs.lnx_x64 }}|g" Formula/skeletor.rb

      - name: Commit & push
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/skeletor.rb
          git commit -m "skeletor: update to ${{ inputs.tag }}" || echo "No changes"
          git push || true
